# Generated by Django 2.2.5 on 2019-09-18 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.PositiveIntegerField()),
                ('flat', models.PositiveIntegerField()),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('flat_size', models.PositiveIntegerField()),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Occupied'), (2, 'Vacant')], default=1)),
                ('phone', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('meter_sr', models.TextField(blank=True, null=True)),
                ('basis', models.PositiveIntegerField(blank=True, choices=[(1, 'N'), (2, 'Y')], null=True)),
                ('fixed_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
