# Generated by Django 2.2.4 on 2019-09-22 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 8, 7, 11, 386204, tzinfo=utc)),
        ),
    ]
