# Generated by Django 2.2 on 2019-09-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionAmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.PositiveIntegerField()),
                ('tower_name', models.CharField(max_length=10)),
                ('eb_price', models.FloatField(verbose_name='Utility Rate')),
                ('dg_price', models.FloatField(verbose_name='DG Rate')),
                ('maintance', models.FloatField()),
                ('fixed_amt', models.FloatField()),
            ],
        ),
    ]
