# Generated by Django 2.2.4 on 2019-09-22 08:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190922_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 8, 40, 39, 592963, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eb', models.FloatField(default=0, verbose_name='Utility KWH')),
                ('dg', models.FloatField(default=0, verbose_name='DG KWH')),
                ('ref_eb', models.FloatField(default=0, verbose_name='Ref Utility KWH')),
                ('ref_dg', models.FloatField(default=0, verbose_name='Ref DG KWH')),
                ('eb_price', models.FloatField(default=0, verbose_name='Utility Rate')),
                ('dg_price', models.FloatField(default=0, verbose_name='DG Rate')),
                ('mrate', models.FloatField(verbose_name='Maintance Rate')),
                ('famt', models.FloatField(verbose_name='Fixed Amount')),
                ('amt_left', models.FloatField()),
                ('dt', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Flats')),
            ],
        ),
    ]
