# Generated by Django 2.2.5 on 2019-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_consumption_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='reset_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
