# Generated by Django 2.2 on 2019-09-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190925_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='amt_left',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Left'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='ng_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Negative DG KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='ng_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Negative Utility KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='ref_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Ref DG KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='ref_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Ref Utility KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='start_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Start DG KWH'),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='start_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Start Utility KWH'),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='dg_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG Rate'),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='eb_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility Rate'),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='fixed_amt',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='maintance',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='maintance',
            name='famt',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Fixed Amount'),
        ),
        migrations.AlterField(
            model_name='maintance',
            name='field_amt',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='maintance',
            name='mcharge',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Maintance Charges'),
        ),
        migrations.AlterField(
            model_name='maintance',
            name='mrate',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Maintance Rate'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='cls_amt',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Closing Amount'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='dg_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG Rate'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='eb_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility Rate'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='end_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='End DG KWH'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='end_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='End Utility KWH'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='opn_amt',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Opening Amount'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='start_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Start DG KWH'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='start_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Start Utility KWH'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='amt_left',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='reading',
            name='dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG KWH'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='dg_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG Rate'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility KWH'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='eb_price',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility Rate'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='famt',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Fixed Amount'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='mrate',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Maintance Rate'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='ref_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Ref DG KWH'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='ref_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Ref Utility KWH'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='amt_left',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Left'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG KWH'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility KWH'),
        ),
    ]
