# Generated by Django 2.2.5 on 2019-09-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190920_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Flats'),
        ),
    ]
