# Generated by Django 2.2.4 on 2019-09-22 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190922_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 14, 57, 5, 339487, tzinfo=utc)),
        ),
    ]
