# Generated by Django 2.2 on 2019-09-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190927_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='ref_dg',
        ),
        migrations.RemoveField(
            model_name='consumption',
            name='ref_eb',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='ref_dg',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='ref_eb',
        ),
    ]
