# Generated by Django 2.2 on 2019-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190927_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='famt',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='mrate',
        ),
        migrations.AlterField(
            model_name='reading',
            name='dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
