# Generated by Django 2.2.4 on 2019-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190922_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
