# Generated by Django 2.2 on 2019-09-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190927_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionamt',
            name='tower',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
