# Generated by Django 2.2 on 2019-09-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190927_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintance',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
