# Generated by Django 2.2 on 2019-09-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190927_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintance',
            old_name='Date',
            new_name='dt',
        ),
    ]
