# Generated by Django 2.2 on 2019-09-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190927_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintance',
            name='field_amt',
        ),
    ]
