# Generated by Django 2.2.4 on 2019-09-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_maintance_field_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybill',
            name='Bill_Pkey',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='sno',
        ),
    ]
