# Generated by Django 2.2 on 2019-10-04 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20191001_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name': 'Consumption', 'verbose_name_plural': 'Consumption'},
        ),
        migrations.AlterModelOptions(
            name='deductionamt',
            options={'verbose_name': 'Deduction Amount', 'verbose_name_plural': 'Deduction Amount'},
        ),
        migrations.AlterModelOptions(
            name='flats',
            options={'verbose_name': 'Flats', 'verbose_name_plural': 'Flats Detail'},
        ),
        migrations.AlterField(
            model_name='recharge',
            name='Type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'cash'), (2, 'bank'), (3, 'neft')], null=True),
        ),
        migrations.CreateModel(
            name='MeterChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_left', models.DecimalField(decimal_places=4, max_digits=19)),
                ('old_meter_sr', models.TextField(blank=True, null=True, verbose_name='Old Meter Serial Number')),
                ('old_start_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start Utility KWH')),
                ('old_ng_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Consumed Utility KWH')),
                ('old_last_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Last Utility KWH')),
                ('old_start_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start DG KWH')),
                ('old_ng_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Consumed DG KWH')),
                ('old_last_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Last DG KWH')),
                ('new_meter_sr', models.TextField(blank=True, null=True, verbose_name='New Meter Serial Number')),
                ('new_start_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start Utility KWH')),
                ('new_start_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start DG KWH')),
                ('dt', models.DateTimeField()),
                ('change_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Flats')),
            ],
        ),
    ]
