# Generated by Django 2.2 on 2019-10-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191005_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amt_left', models.DecimalField(decimal_places=4, max_digits=19)),
                ('old_meter_sr', models.TextField(blank=True, null=True, verbose_name='Old Meter Serial Number')),
                ('old_start_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start Utility KWH')),
                ('old_ng_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Consumed Utility KWH')),
                ('old_last_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Last Utility KWH')),
                ('old_start_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Start DG KWH')),
                ('old_ng_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Consumed DG KWH')),
                ('old_last_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Old Last DG KWH')),
                ('new_meter_sr', models.TextField(blank=True, null=True, verbose_name='New Meter Serial Number')),
                ('new_start_eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='New Start Utility KWH')),
                ('new_start_dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='New Start DG KWH')),
                ('dt', models.DateTimeField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Flats')),
            ],
        ),
    ]
