# Generated by Django 2.2 on 2019-10-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191005_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterchange',
            name='change_by',
        ),
    ]
