# Generated by Django 2.2 on 2019-10-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_meterchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterchange',
            name='dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
