# Generated by Django 2.2 on 2019-10-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_meterchange_change_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_key', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility KWH')),
                ('dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG KWH')),
                ('load', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Running Load')),
                ('f_type', models.PositiveIntegerField(blank=True, choices=[(1, 'cash'), (2, 'bank'), (3, 'neft')], null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='meterchange',
            name='new_start_dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='New Start DG KWH'),
        ),
        migrations.AlterField(
            model_name='meterchange',
            name='new_start_eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='New Start Utility KWH'),
        ),
        migrations.CreateModel(
            name='FeederReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('eb', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Utility KWH')),
                ('dg', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='DG KWH')),
                ('load', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Running Load')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Feeder')),
            ],
        ),
    ]
