# Generated by Django 2.2 on 2019-10-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191009_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_type', models.PositiveIntegerField(choices=[(1, 'Recharge'), (2, 'Low Balance'), (3, 'Negative Balance')])),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Flats')),
                ('m_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.MessageTemplate')),
            ],
        ),
    ]
