# Generated by Django 2.2 on 2019-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191007_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='f_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Incoming'), (2, 'Outgoing')], null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='ps_key',
            field=models.PositiveIntegerField(choices=[(1, 'PS2'), (2, 'PS1')]),
        ),
    ]
