# Generated by Django 2.2 on 2019-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191007_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='dg',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True, verbose_name='DG KWH'),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='eb',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True, verbose_name='Utility KWH'),
        ),
    ]
