# Generated by Django 2.2 on 2019-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_messagetemplate_sentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='m_type',
            field=models.PositiveIntegerField(choices=[(1, 'Recharge'), (2, 'Low Balance'), (3, 'Negative Balance')], unique=True),
        ),
    ]
