# Generated by Django 2.2 on 2019-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191007_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='load',
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True, verbose_name='Running Load'),
        ),
    ]
