# Generated by Django 2.2 on 2019-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191007_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
