# Generated by Django 2.2 on 2019-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191011_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='last_deduction_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
