# Generated by Django 2.2.5 on 2019-10-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20191012_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='last_deduction_dt',
            field=models.DateTimeField(),
        ),
    ]
