# Generated by Django 2.2.7 on 2019-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191031_2202'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='OtherMaintance',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('price', models.PositiveIntegerField()),
        #         ('name', models.CharField(max_length=255)),
        #         ('start_dt', models.DateTimeField()),
        #         ('end_dt', models.DateTimeField(blank=True, null=True)),
        #     ],
        # ),
    ]
