# Generated by Django 2.2.7 on 2019-11-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_othermaintance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermaintance',
            name='end_dt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='othermaintance',
            name='start_dt',
            field=models.DateField(),
        ),
    ]
