# Generated by Django 2.2.7 on 2020-04-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20191111_1602'),
        ('users', '0024_auto_20191112_2123'),
    ]

    operations = [
    ]
