# Generated by Django 2.2.7 on 2020-04-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_merge_20200407_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consumption',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Enough Balance'), (1, 'Low Balance'), (2, 'Negative Balance'), (3, 'Power Cut')], null=True),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='Type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'cash'), (2, 'bank'), (3, 'neft'), (4, 'merchant')], null=True),
        ),
    ]
