# Generated by Django 2.2.7 on 2020-09-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200408_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductionamt',
            name='dg_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='DG Rate'),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='eb_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Utility Rate'),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='fixed_amt',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='deductionamt',
            name='maintance',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
