# Generated by Django 2.2.7 on 2020-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200915_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductionamt',
            name='set_load',
            field=models.FloatField(null=True),
        ),
    ]
