# Generated by Django 2.2 on 2020-10-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_complaint_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default=1),
        ),
    ]
