# Generated by Django 2.2 on 2020-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201016_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='Type',
            field=models.PositiveIntegerField(choices=[(1, 'Penthouse'), (2, '2BHK'), (2, '3BHK')], null=True),
        ),
    ]
