# Generated by Django 2.2 on 2021-01-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_flats_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermaintance',
            name='flat',
            field=models.ManyToManyField(to='users.Flats'),
        ),
    ]
