# Generated by Django 2.2 on 2021-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_othermaintance_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='Type',
            field=models.PositiveIntegerField(choices=[(1, 'Penthouse'), (2, '2BHK'), (3, '3BHK')], null=True),
        ),
        migrations.AlterField(
            model_name='othermaintance',
            name='flat',
            field=models.ManyToManyField(to='users.DeductionAmt'),
        ),
    ]
