# Generated by Django 2.2 on 2021-01-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20210101_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othermaintance',
            old_name='flat',
            new_name='tower',
        ),
    ]
