# Generated by Django 2.2.5 on 2021-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210101_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='Type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Penthouse'), (2, '2BHK'), (3, '3BHK')], null=True),
        ),
    ]
